# Generated by Django 3.2.9 on 2021-12-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='actors',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='rates',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
