# Generated by Django 3.2.9 on 2021-12-01 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereview', '0003_alter_post_watched_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='watched_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
