# Generated by Django 3.2.9 on 2021-11-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deulapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='cat',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='prefer_animal',
            field=models.CharField(choices=[('강아지', '강아지'), ('고양이', '고양이')], default='', max_length=3, verbose_name='좋아하는 동물'),
        ),
    ]
