# Generated by Django 3.2.9 on 2021-12-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orange', '0002_alter_music_released_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='korean_music',
            field=models.BooleanField(default=True),
        ),
    ]
