# Generated by Django 3.2.9 on 2021-12-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
