# Generated by Django 3.2.9 on 2021-12-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='poster',
            new_name='poster_file',
        ),
    ]
