# Generated by Django 3.2.9 on 2021-12-09 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
